### ISSUE TITLE
Access the OpenVAS web page remotely

### ISSUE THREAD

**Issue by JeanMTX** [bgilmer77/HowTo-Configure-OpenVAS#1]
hi,

In the section Access the OpenVAS web page remotely

It says Edit the line containing ExecStart as indicated below
ExecStart=/usr/sbin/gsad --foreground --listen=0.0.0.0 --port=9392 --mlisten=0.0.0.0 --mport=9390 --allow-header-host [PUBLIC-IP-ADDRESS]

But the file contains the following line
ExecStart=/usr/sbin/openvasmd --listen=127.0.0.1 --port=9390 --database=/var/lib/openvas/mgr/tasks.db

Is this an error or I am supposed to change the whole content from running openvasmd to gsad?
Because this does not seem to work...

thank you.

**Comment by bgilmer77** [comment]
Thank you for posting this issue.  The OpenVAS code has changed.  I am buried in some other tasks, but will get to this as soon as I can.  I looked quickly for an answer and found the link below.  If you have time, maybe you can test this to see if it works and let me know?

[https://superuser.com/questions/977331/how-to-make-openvas-listen-on-an-external-interface for article on how to enable OpenVAS access from another computer](url)

**Comment by bgilmer77** [comment]
Hi @JeanMTX , I have now had a chance to dig into this.  It appears that the option `--allow-header-host` has been removed from the codebase.  I will delete this note about remote access from the HowTo.  If you or someone else figures it out, please add an Issue and I will modify the document.
Thanks for your input.

**Comment by bgilmer77** [comment]
Document modified, adding note asking for help if someone figures out how to get remote access.
