### ISSUE TITLE
Issues / questions from install process

### ISSUE THREAD

**Issue by firthmj** [bgilmer77/HowTo-Configure-OpenVAS#2]
When installing OpenVAS, I'm getting the error "Failed to execute default Web Browser. Input/output error."  - is this something that's been seen before?

Am I right that the section labelled "Updating OpenVAS Network Vulnerability Tests (NVTs)" effectively already happens as part of the initial install process, so doesn't need to be done immediately afterwards?

I think the "packages held back" message can be fixed by using "apt dist-upgrade -y" instead of just "apt upgrade -y" - "apt upgrade -y" won't try and upgrade the kernel, for example.

Finally, I think using "sudo su -" to get a root shell is discouraged by some guides, which suggest that "sudo -i" is a better command to use.

**Comment by bgilmer77** [comment]
@firthmj, Thanks for raising the issues:
-  Web browser error
I have not seen this error before, so I cannot help with that unfortunately.

-  Updating NVTs
Yes - you are correct.  The initial installation downloads the latest NVTs, so I will make that clear in the document.

-  Packages held back
I will change the document to include apt dist-upgrade

-  sudo
I will change to sudo -i

Thanks for your comments.
