### ISSUE TITLE
Include instructions on how to access the webpage on an external interface

### ISSUE THREAD

**Issue by isaacgr** [bgilmer77/HowTo-Configure-OpenVAS#3]
So I have this setup. But I wanted to access the webpage from an external interface, not locally on the machine. Heres what worked.

Edited **/lib/systemd/system/greenbone-security-assistant.service** to use 0.0.0.0 as the listening IP address, and included the external IP as the host header (otherwise you get **The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.** when trying to accesss port 9392).

```
[Unit]
Description=Greenbone Security Assistant
Documentation=man:gsad(8) http://www.openvas.org/ 8
Wants=openvas-manager.service

[Service]
Type=simple
PIDFile=/var/run/gsad.pid
ExecStart=/usr/sbin/gsad --foreground --listen=0.0.0.0 --port=9392 --mlisten=0.0.0.0 --mport=9390 --allow-header-host my_external_ip
```
```
root@KALI:~# systemctl daemon-reload
root@KALI:~# systemctl restart greenbone-security-assistant.service
```

**Comment by isaacgr** [comment]
Nvm.

**Comment by bgilmer77** [comment]
@isaacgr, nvm because it does not work?

**Comment by bgilmer77** [comment]
No further input.  Closing this issue.
